---
# tasks file for hello-world
- name: stop apache2
  service:
    state: stopped
    named: apache2

- name: Install nginx
  apt:
    state: present
    name: nginx
    update_cache: yes
- name: Copy Hello-world vhost conf
  copy:
    src: hello-world
    dest: /etc/nginx/sites-available/hello-world
- name: Symlink
  file:
    src: /etc/nginx/sites-available/hello-world
    dest: /etc/nginx/sites-enabled/hello-world
    state: link

- name: Create html folder
  file:
    state: directory
    path: /opt/hello-world
    owner: www-data
    group: www-data

- name: render from tempalte index.html
  template:
    src: index.html.j2
    dest: /opt/hello-world/index.html
    owner: www-data
    group: www-data
- name: restart nginx
  service:
    state: restarted
    named: nginx

